name: Compare function
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          CO: ${{ contains(github.event.issue.labels.*.name, 'bug' }}
