name: Compare function
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: conver json
        env:
          CONTEXT: ${{ toJSON(github) }}
        run: echo "${CONTEXT}}"
      - name: hash
        env:
          HASH ${{ hashFile('.github/workflows/*.yml') }}
        run: echo "${HASH}"