name: Compare function
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate a failure
        run: exit 0

      - if: ${{ success() }}
        name: Print HELLO if previous step failed
        run: echo "HELLO"
