name: Compare function
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: conver json
        env:
          CONTEXT: ${{ toJSON(github) }}
        run: echo "${CONTEXT}}"
      - if: ${{ contains(github.run_id, '1') }}
        run: echo "HELLO"

